
name: CI Pipeline

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 20.x
      uses: actions/setup-node@v1
      with:
        node-version: 20.x
    - run: npm ci
    - run: npm run build --if-present
    - name: run tests
      run: npm run test
      continue-on-error: true

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage/lcov.info
